# Generated by Django 5.0.3 on 2024-03-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_critics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='star',
        ),
    ]
